### ISSUE TITLE
Fix node tests

### ISSUE THREAD

**Issue by kezike** [digitalcredentials/status-list-manager-git#4]
Context: After refactoring the status library to be compatible with vanilla Javascript client code, we are encountering the following error with the node tests: `TypeError: ES Modules cannot be stubbed`. This error originates from the Sinon library and relates to the fact that ESM modules cannot be modified.

Reproduction: Run `yarn test-node` or simply `yarn test`.

Deliverable: Fix node tests and remove `FIXME` comment in `.github/workflows/main.yml`.

**Comment by kayaelle** [comment]
Addressed by PR https://github.com/digitalcredentials/status-list-manager-git/pull/2
