### ISSUE TITLE
Add support for personal workspaces

### ISSUE THREAD

**Issue by kezike** [digitalcredentials/status-list-manager-git#5]
Context: Currently, this library can only create credential status artifacts within an organizational workspace. This design shirks DCC's mandate to provide simple and accessible tools that enable more issuers to get started as quickly as possible.

Deliverable: Add support for creating credential status artifacts within a personal workspace.

**Comment by kayaelle** [comment]
Addressed by PR https://github.com/digitalcredentials/status-list-manager-git/pull/2
